### ISSUE TITLE
Clicking Load more in news menu doesnt load more and it hangs the launcher

### ISSUE THREAD

**Issue by MuhammadUsmanMithani** [Nishant1500/bee-launcher#12]
when u click out of launcher aft that, launcher hangs and u cant bring windowsto focus
u have to close window and open new window of it

**Comment by Nishant1500** [comment]
Thank You For Submitting A Bug Report. We Appreciate Your Contribution :) , We Will Soon Look Onto This Bug And Fix It As Soon As We Can. 

**PS**: If You Are In Our Discord You Will Get A Bug Hunter Role.

Happy Bug Hunting!

**Comment by Nishant1500** [comment]
**Status Page Updated!**
Thank You So Much For Reporting, We Really Appreciate It!

Incident/Issue ID - 77800
Incident/Issue Link - [**On Clicking "Load More" In News Tab, Bee Launcher Stop Responding**](http://status.bee-launcher.ga/incident/77800)

Know More About Other Incidents And Maintenance At Our [**Status Page**](http://status.bee-launcher.ga/)

**Comment by Nishant1500** [comment]
Hello There!

I Am Unable To Reproduce This Bug Can You Show A **GIF or Video** Reproducing the Bug? It Would be appreciated!

**Comment by MuhammadUsmanMithani** [comment]
nvm it fixed smh
i updated node so prolly thats why
